### ISSUE TITLE
Single sign-on integration

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-backend#105]

**Comment by jswatsch** [comment]
TORCHLITE MongoDB that handles the dashboard, needs to convert AG workset to TORCHLITE workset ID

**Comment by jswatsch** [comment]
Talking to Boris about how to update our database with necessary changes.

**Comment by dkudeki** [comment]
Public Analytics Gateway worksets are now live as of https://github.com/htrc/torchlite-frontend/commit/93808b1e8b77ac9f1f762dab22db8c8bbf6444df and https://github.com/htrc/torchlite-backend/commit/a4cd41836cd08d653b4dde98332daa9bd6ed94ce. "My Worksets" searches the list of public worksets that have been created by the logged-in user. We'll need a second API call to AG with authentication if we want to populate this with a user's private worksets.

Right now All and My worksets have a limit of 1000 volumes

**Comment by jchristie01** [comment]
@dkudeki info on how to connect to AG to get a working version soon (1-2 weeks).
