### ISSUE TITLE
Backend: caching data

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-backend#111]

**Comment by sandeep-ps** [comment]
Working on a first draft implementation of caching with https://github.com/long2ice/fastapi-cache and am currently testing the /worksites endpoint.

**Comment by sandeep-ps** [comment]
Sharing initial results of caching when running things locally with Redis as the caching database. The below results are for the endpoint: GET /worksets/{{worksetId}}/metadata. I'm seeing a 55% reduction in the average response time. :-D

1. With cache **enabled**
![Image](https://github.com/user-attachments/assets/3143bf8f-3145-47c0-a79c-75a2db1c9810)
2. With cache **disabled** 
![Image](https://github.com/user-attachments/assets/2d472031-7831-43c8-86ef-10af77a7af06)

I will proceed with implementing this for different endpoints in the TORCHLITE backend. Please let me know if you have any questions or concerns. Thanks.

CC: @dkudeki, @gworthey

**Comment by gworthey** [comment]
That’s great news, Sandeep — thanks!

On Aug 1, 2024, at 1:36 PM, Sandeep Puthanveetil Satheesan ***@***.***> wrote:



Sharing initial results of caching when running things locally with Redis as the caching database. The below results are for the endpoint: GET /worksets/{{worksetId}}/metadata. I'm seeing a 55% reduction in the average response time. :-D

  1.  With cache enabled
image.png (view on web)<https://urldefense.com/v3/__https://github.com/user-attachments/assets/3143bf8f-3145-47c0-a79c-75a2db1c9810__;!!DZ3fjg!8Sto3zE_3bqOa3gMvNrex4dx-A67M2YBToatkfxaFtQpLinHCqsqdAJFX3sHSBLZjN39V8PNu0AytRgBIoAgLLDvgLoP$>
  2.  With cache disabled
image.png (view on web)<https://urldefense.com/v3/__https://github.com/user-attachments/assets/2d472031-7831-43c8-86ef-10af77a7af06__;!!DZ3fjg!8Sto3zE_3bqOa3gMvNrex4dx-A67M2YBToatkfxaFtQpLinHCqsqdAJFX3sHSBLZjN39V8PNu0AytRgBIoAgLAQrWkns$>

I will proceed with implementing this for different endpoints in the TORCHLITE backend. Please let me know if you have any questions or concerns. Thanks.

CC: @dkudeki<https://urldefense.com/v3/__https://github.com/dkudeki__;!!DZ3fjg!8Sto3zE_3bqOa3gMvNrex4dx-A67M2YBToatkfxaFtQpLinHCqsqdAJFX3sHSBLZjN39V8PNu0AytRgBIoAgLD19SQqc$>, @gworthey<https://urldefense.com/v3/__https://github.com/gworthey__;!!DZ3fjg!8Sto3zE_3bqOa3gMvNrex4dx-A67M2YBToatkfxaFtQpLinHCqsqdAJFX3sHSBLZjN39V8PNu0AytRgBIoAgLLXvw45L$>

**Comment by jswatsch** [comment]
@dkudeki is reviewing pull request as of 9/5/2024

**Comment by jswatsch** [comment]
@dkudeki added a patch for a bug related to internal API calls. The bug seems to be isolated to internal endpoint calls, not a broader problem with caching.

@sandeep can deploy it to the development stack

**Comment by jswatsch** [comment]
@sandeep-ps deployed in dev instance.
