### ISSUE TITLE
create list of HTRC worksets

### ISSUE THREAD

**Issue by cwulfman** [htrc/torchlite-backend#4]
This database needs to be created and curated by HTRC.  HTRC needs to provide us with an API to this database, or a way to import it into the Torchlite app.

Corresponding with the wireframe, the database must include

- workset id  This is the id of the workset in the EF database

- workset name

- workset creator name

- workset description

**Comment by jswatsch** [comment]
| Name   | Workset ID | # of Volumes | Description | Author
| ------ | -------- | --------| --------| --------|
| Native-authored Workset | 6408a5e930000067055ce2e8 |<center>919</center>| A list of works authored by Native Americans in HathiTrust| SCWAReD |
| Comparative Literature Workset | 6408a63a30000067055ce2e9 |<center>927</center>|A list of works authored by non-Native Americans in HathiTrust on the similar subjects as the Native-authored workset during similar time period with similar language representation | SCWAReD |
| The Black Fantastic Workset | 642720e53300008d02a5dc9c |<center>90</center> |90 volumes, including duplicates, of Black Fantastic fiction, identified by Dr. Seretha Williams and Dr. Clarissa West-White, as part of HTRC's SCWAReD project |  SCWAReD |
| History of Black Writers Workset | 6407a1ec300000a4045ce2e7 | <center>2166</center> | Volumes found in HathiTrust written by African-American authors, as identified by the University of Kansas's Project on the History of Black Writing, released as part of the SCWAReD project| SCWAReD |
| History of Black Writers Workset Sample | 640ba4bf300000440a5ce31a | <center>25</center> | 25 volume sample of volumes found in HathiTrust written by African-American authors, as identified by the University of Kansas's Project on the History of Black Writing, released as part of the SCWAReD project | SCWAReD |
